### ISSUE TITLE
Snagging list

### ISSUE THREAD

**Issue by philbarker** [pesc-org/json-ld-transcript#16]
Queries arising from other issues that need wider discussion before decision can be made:

**In Students Name:**
- [ ] compositeName is a legacy field, not widely used. Probably doesn't matter much. displayName would be more useful (optional). Could use full name from CEDS.
- [ ] Probably ought to expand enumeration to include things like preferredName.

**Comment by 4pins** [comment]
Sounds right.  Our approach is similar but diffrent.

http://specification.sifassociation.org/Implementation/NA/4.3/CommonTypes.html#obj:BaseNameType

**Comment by philbarker** [comment]
- [ ] What more specific types of educaitonal orgaziton do we need.
- [ ] What levels do we need.

**Comment by 4pins** [comment]
@philbarker Is this where you meant to make the most recent comment.  From my point of view, it doesn't fit in this (closed) ticket.

**Comment by philbarker** [comment]
Yeah, this is just a tracking issue for miscellanea we need to pick up on later.  It's not closed.

**Comment by philbarker** [comment]
In Organization Identification
- [ ] Need to figure out how best to relax constraints so that implementers can use their own Ord ID scheme, hopefully while still warning if no recognized scheme is present.

Currently must have one of the recognized schemes.

**Comment by philbarker** [comment]
Names (mostly organization)
- [ ] Org names in CEDS are tokens, we need langStrings.

Requires change in CEDS or us to do something different to CEDS.

**Comment by philbarker** [comment]
Residency (and address??)
- [ ] Country code should come from a (long) picklist
- [ ] State code should come from a (long) picklist

**Comment by philbarker** [comment]
In LanguageShape and language of instruction
- [ ] the only test is that the language code is an alpha-3 string; no test that it is a valid ISO 639-2 code.
- [ ] are extended codes allowed?

**Comment by philbarker** [comment]
Need to make sure that each individual tap sheet has enough of the shapes to check the type of objects that are in other tap sheets. For example, no use saying that targetContactPoint has value shape ContactPointShape if nothing of that shape is defined. It's enough to define the expected type as rest can be checked in the relevant TAP sheet.

**Comment by philbarker** [comment]
- [ ] Check whether this change https://github.com/CEDStandards/CEDS-Ontology/commit/64aca2510349ed2d981de03778e02e90f4bcb0d2 in CEDS makes any difference to our organization IDs
